force-app/main/default/objects/Data_Translation__c/Data_Translation__c.object-meta.xml
<CustomObject>
    <label>Data Translation</label>
    <nameField>
        <displayFormat>DT-{00000}</displayFormat>
        <label>Survey Translation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Translations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Translation__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>en_US</fullName>
                <label>English</label>
            </value>
            <value>
                <fullName>de</fullName>
                <label>German</label>
            </value>
            <value>
                <fullName>es</fullName>
                <label>Spanish</label>
            </value>
            <value>
                <fullName>fr</fullName>
                <label>French</label>
            </value>
            <value>
                <fullName>it</fullName>
                <label>Italian</label>
            </value>
            <value>
                <fullName>ja</fullName>
                <label>Japanese</label>
            </value>
            <value>
                <fullName>sv</fullName>
                <label>Swedish</label>
            </value>
            <value>
                <fullName>ko</fullName>
                <label>Korean</label>
            </value>
            <value>
                <fullName>zh_TW</fullName>
                <label>Chinese (Traditional)</label>
            </value>
            <value>
                <fullName>zh_CN</fullName>
                <label>Chinese (Simplified)</label>
            </value>
            <value>
                <fullName>pt_BR</fullName>
                <label>Portuguese (Brazil)</label>
            </value>
            <value>
                <fullName>nl_NL</fullName>
                <label>Dutch</label>
            </value>
            <value>
                <fullName>da</fullName>
                <label>Danish</label>
            </value>
            <value>
                <fullName>th</fullName>
                <label>Thai</label>
            </value>
            <value>
                <fullName>fi</fullName>
                <label>Finnish</label>
            </value>
            <value>
                <fullName>ru</fullName>
                <label>Russian</label>
            </value>
            <value>
                <fullName>es_MX</fullName>
                <label>Spanish (Mexico)</label>
            </value>
            <value>
                <fullName>no</fullName>
                <label>Norwegian</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Translation__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Translation__c/fields/Translated_Value__c.field-meta.xml
<CustomField>
    <fullName>Translated_Value__c</fullName>
    <label>Translated Value</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/LexicoTest.cls
/**
    MIT License

    Copyright (c) 2020 4an70m

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
 */
@IsTest
public with sharing class LexicoTest {

    //Lexico
    @IsTest
    public static void testLexicoNoData() {
        final Account account = new Account(Name = 'Test');
        insert account;

        final List<Account> accounts = Lexico.getInstance().translate('es', [SELECT Id, Name FROM Account]);

        System.assertEquals(1, accounts.size());
        System.assertEquals('Test', accounts[0].Name);
    }

    @IsTest
    public static void testLexicoNoRecords() {
        final List<Account> accounts = Lexico.getInstance().translate('es', [SELECT Id, Name FROM Account]);

        System.assert(accounts.isEmpty());
    }

    @IsTest
    public static void testLexicoBadData() {
        final List<Account> accounts = Lexico.getInstance().translate('es', null);

        System.assert(accounts.isEmpty());
    }

    @IsTest
    public static void testLexicoWithData() {
        final Account account = new Account(Name = 'Test');
        insert account;

        final Data_Translation__c accountNameDt = new Data_Translation__c(
                Record_Id__c = account.Id,
                Field_API_Name__c = 'Name',
                Language__c = 'es',
                Translated_Value__c = 'Test in spanish'
        );
        insert accountNameDt;

        final List<Account> accounts = Lexico.getInstance().translate('es', [SELECT Id, Name FROM Account]);

        System.assertEquals(1, accounts.size());
        System.assertEquals('Test in spanish', accounts[0].Name);
    }

    @IsTest
    public static void testLexicoWithCache() {
        final Account account = new Account(Name = 'Test');
        insert account;

        final Data_Translation__c accountNameDt = new Data_Translation__c(
                Record_Id__c = account.Id,
                Field_API_Name__c = 'Name',
                Language__c = 'es',
                Translated_Value__c = 'Test in spanish'
        );
        insert accountNameDt;

        List<Account> accounts = Lexico.getInstance().translate('es', [SELECT Id, Name FROM Account]);
        accounts = Lexico.getInstance().translate('es', [SELECT Id, Name FROM Account]);

        System.assertEquals(1, accounts.size());
        System.assertEquals('Test in spanish', accounts[0].Name);
    }

    @IsTest
    public static void testLexicoWithDataAndRefresh() {
        final Account account = new Account(Name = 'Test');
        insert account;

        final Data_Translation__c accountNameDt = new Data_Translation__c(
                Record_Id__c = account.Id,
                Field_API_Name__c = 'Name',
                Language__c = 'es',
                Translated_Value__c = 'Test in spanish'
        );
        insert accountNameDt;

        final List<Account> accounts = Lexico.getInstance().translate('es', [SELECT Id, Name FROM Account], true);

        System.assertEquals(1, accounts.size());
        System.assertEquals('Test in spanish', accounts[0].Name);
    }
}